name = input("名前を入力してください：")
age = input("年齢を入力してください：")
food = input("好きな食べ物はなんですか？：")
print("入力ありがとうございました！")
input("Enterでプロフィールを表示します")
print("===================")
print("プロフィール")
print("===================")
print()
print(f"名前：{name}")
print("年齢：", end="")
print(age, end="")
print("歳")
print("好きな食べ物：" + food)
print()
print("===================")